=== RokLenarcic/poptavka/integration-test-base/src/main/resources/test.dtd
<!ELEMENT dataset (
    ACCESSROLE*,
    ACCESS_ROLE_PERMISSION*,
    ACTION*,
    ACTIVATIONEMAIL*,
    ADDRESS*,
    ADVICE*,
    BASICAUDITINFO*,
    BUSINESSUSER*,
    BUSINESSUSERDATA*,
    BUSINESSUSERDATA_AUD*,
    BUSINESSUSERROLE*,
    BUSINESSUSERROLE_AUD*,
    BUSINESSUSER_ADDRESS*,
    BUSINESSUSER_AUD*,
    BUSINESSUSER_INVOICE*,
    CATEGORY*,
    CLIENT*,
    CLIENT_AUD*,
    DEMAND*,
    DEMANDTYPE*,
    DEMANDTYPE_AUD*,
    DEMAND_AUD*,
    DEMAND_CATEGORY*,
    DEMAND_EXCLUDED_SUPPLIER*,
    DEMAND_EXCLUDED_SUPPLIER_AUD*,
    DEMAND_LOCALITY*,
    EXTERNALCATEGORY*,
    EXTERNALSOURCE*,
    EXTERNAL_CATEGORY_TO_CATEGORY*,
    INVOICE*,
    INVOICE_USERSERVICE*,
    LOCALITY*,
    MESSAGE*,
    MESSAGEUSERROLE*,
    NOTIFICATION*,
    NOTIFICATIONITEM*,
    OFFER*,
    OFFERSTATE*,
    ORIGIN*,
    OURPAYMENTDETAILS*,
    OURPAYMENTDETAILS_AUD*,
    PARTNER*,
    PARTNER_AUD*,
    PAYMENTMETHOD*,
    PERMISSION*,
    PREFERENCE*,
    PREFERENCE_AUD*,
    PROBLEM*,
    PROBLEM_AUD*,
    RATING*,
    REGIONABBREVIATION*,
    REVINFO*,
    SERVICE*,
    SETTINGST*,
    SUPPLIER*,
    SUPPLIERBLACKLIST*,
    SUPPLIERBLACKLIST_SUPPLIER*,
    SUPPLIER_AUD*,
    SUPPLIER_CATEGORY*,
    SUPPLIER_LOCALITY*,
    TEMPLATE*,
    USERCONTACT*,
    USERMESSAGE*,
    USERSERVICE*,
    USERSERVICE_AUD*,
    USERT*,
    USERT_ACCESSROLE*,
    USERT_AUD*)>

<!ELEMENT ACCESSROLE EMPTY>
<!ATTLIST ACCESSROLE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT ACCESS_ROLE_PERMISSION EMPTY>
<!ATTLIST ACCESS_ROLE_PERMISSION
    ACCESSROLE_ID CDATA #REQUIRED
    PERMISSIONS_ID CDATA #REQUIRED
>

<!ELEMENT ACTION EMPTY>
<!ATTLIST ACTION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT ACTIVATIONEMAIL EMPTY>
<!ATTLIST ACTIVATIONEMAIL
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ACTIVATIONCODE CDATA #IMPLIED
    VALIDTO CDATA #IMPLIED
>

<!ELEMENT ADDRESS EMPTY>
<!ATTLIST ADDRESS
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ADDRESSTYPE CDATA #IMPLIED
    FLATNUM CDATA #IMPLIED
    HOUSENUM CDATA #IMPLIED
    STREET CDATA #REQUIRED
    ZIPCODE CDATA #IMPLIED
    CITY_ID CDATA #REQUIRED
>

<!ELEMENT ADVICE EMPTY>
<!ATTLIST ADVICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    BOUNTY CDATA #IMPLIED
    PAYMENTDATE CDATA #IMPLIED
    RECOGNIZED CDATA #IMPLIED
    REMITTERACCOUNT CDATA #IMPLIED
    REMITTERNAME CDATA #IMPLIED
    REMITTERSURNAME CDATA #IMPLIED
    VARIABLESYMBOL CDATA #IMPLIED
    INVOICE_ID CDATA #IMPLIED
>

<!ELEMENT BASICAUDITINFO EMPTY>
<!ATTLIST BASICAUDITINFO
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    INSERTTIME CDATA #IMPLIED
    MODIFICATIONTIME CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    USERIDCREATED CDATA #IMPLIED
    USERIDMODIFIED CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSER EMPTY>
<!ATTLIST BUSINESSUSER
    BUSINESSTYPE CDATA #IMPLIED
    ID CDATA #REQUIRED
    BUSINESSUSERDATA_ID CDATA #REQUIRED
    ORIGIN_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERDATA EMPTY>
<!ATTLIST BUSINESSUSERDATA
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    COMPANYNAME CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PERSONFIRSTNAME CDATA #REQUIRED
    PERSONLASTNAME CDATA #REQUIRED
    PHONE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    WEBSITE CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERDATA_AUD EMPTY>
<!ATTLIST BUSINESSUSERDATA_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    COMPANYNAME CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PERSONFIRSTNAME CDATA #IMPLIED
    PERSONLASTNAME CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    WEBSITE CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERROLE EMPTY>
<!ATTLIST BUSINESSUSERROLE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    VERIFICATION CDATA #IMPLIED
    BUSINESSUSER_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERROLE_AUD EMPTY>
<!ATTLIST BUSINESSUSERROLE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    VERIFICATION CDATA #IMPLIED
    BUSINESSUSER_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSER_ADDRESS EMPTY>
<!ATTLIST BUSINESSUSER_ADDRESS
    BUSINESSUSER_ID CDATA #REQUIRED
    ADDRESSES_ID CDATA #REQUIRED
>

<!ELEMENT BUSINESSUSER_AUD EMPTY>
<!ATTLIST BUSINESSUSER_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    BUSINESSTYPE CDATA #IMPLIED
    BUSINESSUSERDATA_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSER_INVOICE EMPTY>
<!ATTLIST BUSINESSUSER_INVOICE
    BUSINESSUSER_ID CDATA #REQUIRED
    INVOICES_ID CDATA #REQUIRED
>

<!ELEMENT CATEGORY EMPTY>
<!ATTLIST CATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    LEFTBOUND CDATA #IMPLIED
    LEVEL CDATA #REQUIRED
    RIGHTBOUND CDATA #IMPLIED
    TREEID CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
    PARENT_ID CDATA #IMPLIED
    TEMPLATE_ID CDATA #IMPLIED
>

<!ELEMENT CLIENT EMPTY>
<!ATTLIST CLIENT
    OVERALRATING CDATA #IMPLIED
    ID CDATA #REQUIRED
>

<!ELEMENT CLIENT_AUD EMPTY>
<!ATTLIST CLIENT_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    OVERALRATING CDATA #IMPLIED
>

<!ELEMENT DEMAND EMPTY>
<!ATTLIST DEMAND
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ATTACHMENTPATH CDATA #IMPLIED
    CREATEDDATE CDATA #IMPLIED
    DESCRIPTION CDATA #REQUIRED
    ENDDATE CDATA #IMPLIED
    MAXSUPPLIERS CDATA #IMPLIED
    MINRATING CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    STATUS CDATA #REQUIRED
    TITLE CDATA #REQUIRED
    VALIDTO CDATA #IMPLIED
    CLIENT_ID CDATA #IMPLIED
    ORIGIN_ID CDATA #IMPLIED
    RATING_ID CDATA #IMPLIED
    TYPE_ID CDATA #REQUIRED
>

<!ELEMENT DEMANDTYPE EMPTY>
<!ATTLIST DEMANDTYPE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT DEMANDTYPE_AUD EMPTY>
<!ATTLIST DEMANDTYPE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT DEMAND_AUD EMPTY>
<!ATTLIST DEMAND_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    ATTACHMENTPATH CDATA #IMPLIED
    CREATEDDATE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    ENDDATE CDATA #IMPLIED
    MAXSUPPLIERS CDATA #IMPLIED
    MINRATING CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    VALIDTO CDATA #IMPLIED
    CLIENT_ID CDATA #IMPLIED
    TYPE_ID CDATA #IMPLIED
>

<!ELEMENT DEMAND_CATEGORY EMPTY>
<!ATTLIST DEMAND_CATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CATEGORY_ID CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
>

<!ELEMENT DEMAND_EXCLUDED_SUPPLIER EMPTY>
<!ATTLIST DEMAND_EXCLUDED_SUPPLIER
    DEMAND_ID CDATA #REQUIRED
    SUPPLIER_ID CDATA #REQUIRED
>

<!ELEMENT DEMAND_EXCLUDED_SUPPLIER_AUD EMPTY>
<!ATTLIST DEMAND_EXCLUDED_SUPPLIER_AUD
    REV CDATA #REQUIRED
    DEMAND_ID CDATA #REQUIRED
    SUPPLIER_ID CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
>

<!ELEMENT DEMAND_LOCALITY EMPTY>
<!ATTLIST DEMAND_LOCALITY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
    LOCALITY_ID CDATA #IMPLIED
>

<!ELEMENT EXTERNALCATEGORY EMPTY>
<!ATTLIST EXTERNALCATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    EXTERNALID CDATA #REQUIRED
    EXTERNALSOURCE_ID CDATA #IMPLIED
>

<!ELEMENT EXTERNALSOURCE EMPTY>
<!ATTLIST EXTERNALSOURCE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    URL CDATA #IMPLIED
>

<!ELEMENT EXTERNAL_CATEGORY_TO_CATEGORY EMPTY>
<!ATTLIST EXTERNAL_CATEGORY_TO_CATEGORY
    EXTERNAL_CATEGORY_ID CDATA #REQUIRED
    CATEGORY_ID CDATA #REQUIRED
>

<!ELEMENT INVOICE EMPTY>
<!ATTLIST INVOICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BANKACCOUNTNUMBER CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    CONSTSYMBOL CDATA #IMPLIED
    DUEDATE CDATA #IMPLIED
    INVOICENUMBER CDATA #IMPLIED
    ISSUEDATE CDATA #IMPLIED
    SHIPMENTDATE CDATA #IMPLIED
    TAXBASIS CDATA #IMPLIED
    TOTALPRICE CDATA #IMPLIED
    VARIABLESYMBOL CDATA #IMPLIED
    VAT CDATA #IMPLIED
    VATRATE CDATA #REQUIRED
    PAYMENTMETHOD_ID CDATA #IMPLIED
>

<!ELEMENT INVOICE_USERSERVICE EMPTY>
<!ATTLIST INVOICE_USERSERVICE
    INVOICE_ID CDATA #REQUIRED
    USERSERVICES_ID CDATA #REQUIRED
>

<!ELEMENT LOCALITY EMPTY>
<!ATTLIST LOCALITY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    LEFTBOUND CDATA #IMPLIED
    LEVEL CDATA #REQUIRED
    RIGHTBOUND CDATA #IMPLIED
    TREEID CDATA #IMPLIED
    NAME CDATA #IMPLIED
    TYPE CDATA #IMPLIED
    PARENT_ID CDATA #IMPLIED
>

<!ELEMENT MESSAGE EMPTY>
<!ATTLIST MESSAGE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BODY CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    LASTMODIFIED CDATA #IMPLIED
    MESSAGESTATE CDATA #IMPLIED
    SENT CDATA #IMPLIED
    SUBJECT CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
    FIRSTBORN_ID CDATA #IMPLIED
    NEXTSIBLING_ID CDATA #IMPLIED
    OFFER_ID CDATA #IMPLIED
    PARENT_ID CDATA #IMPLIED
    PROBLEM_ID CDATA #IMPLIED
    SENDER_ID CDATA #IMPLIED
    THREADROOT_ID CDATA #IMPLIED
>

<!ELEMENT MESSAGEUSERROLE EMPTY>
<!ATTLIST MESSAGEUSERROLE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    MESSAGECONTEXT CDATA #IMPLIED
    TYPE CDATA #IMPLIED
    MESSAGE_ID CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT NOTIFICATION EMPTY>
<!ATTLIST NOTIFICATION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    MESSAGETEMPLATE CDATA #IMPLIED
    NAME CDATA #IMPLIED
    NOTIFICATIONTYPE CDATA #IMPLIED
>

<!ELEMENT NOTIFICATIONITEM EMPTY>
<!ATTLIST NOTIFICATIONITEM
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    PERIOD CDATA #IMPLIED
    NOTIFICATION_ID CDATA #IMPLIED
    SETTINGS_ID CDATA #IMPLIED
>

<!ELEMENT OFFER EMPTY>
<!ATTLIST OFFER
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    FINISHDATE CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
    STATE_ID CDATA #IMPLIED
    SUPPLIER_ID CDATA #IMPLIED
>

<!ELEMENT OFFERSTATE EMPTY>
<!ATTLIST OFFERSTATE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT ORIGIN EMPTY>
<!ATTLIST ORIGIN
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
    URL CDATA #IMPLIED
>

<!ELEMENT OURPAYMENTDETAILS EMPTY>
<!ATTLIST OURPAYMENTDETAILS
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BANKACCOUNT CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    CITY CDATA #IMPLIED
    COUNTRYVAT CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    IBAN CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    STREET CDATA #IMPLIED
    SWIFTCODE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    ZIPCODE CDATA #IMPLIED
>

<!ELEMENT OURPAYMENTDETAILS_AUD EMPTY>
<!ATTLIST OURPAYMENTDETAILS_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    BANKACCOUNT CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    CITY CDATA #IMPLIED
    COUNTRYVAT CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    IBAN CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    STREET CDATA #IMPLIED
    SWIFTCODE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    ZIPCODE CDATA #IMPLIED
>

<!ELEMENT PARTNER EMPTY>
<!ATTLIST PARTNER
    ID CDATA #REQUIRED
>

<!ELEMENT PARTNER_AUD EMPTY>
<!ATTLIST PARTNER_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
>

<!ELEMENT PAYMENTMETHOD EMPTY>
<!ATTLIST PAYMENTMETHOD
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT PERMISSION EMPTY>
<!ATTLIST PERMISSION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT PREFERENCE EMPTY>
<!ATTLIST PREFERENCE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    PKEY CDATA #IMPLIED
    VALUE CDATA #IMPLIED
    SETTINGS_ID CDATA #IMPLIED
>

<!ELEMENT PREFERENCE_AUD EMPTY>
<!ATTLIST PREFERENCE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    PKEY CDATA #IMPLIED
    VALUE CDATA #IMPLIED
>

<!ELEMENT PROBLEM EMPTY>
<!ATTLIST PROBLEM
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    TEXT CDATA #IMPLIED
>

<!ELEMENT PROBLEM_AUD EMPTY>
<!ATTLIST PROBLEM_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    TEXT CDATA #IMPLIED
>

<!ELEMENT RATING EMPTY>
<!ATTLIST RATING
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CLIENTMESSAGE CDATA #IMPLIED
    CLIENTRATING CDATA #IMPLIED
    SUPPLIERMESSAGE CDATA #IMPLIED
    SUPPLIERRATING CDATA #IMPLIED
>

<!ELEMENT REGIONABBREVIATION EMPTY>
<!ATTLIST REGIONABBREVIATION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ABBREVIATION CDATA #IMPLIED
    REGION_ID CDATA #IMPLIED
>

<!ELEMENT REVINFO EMPTY>
<!ATTLIST REVINFO
    REV CDATA #REQUIRED
    REVTSTMP CDATA #IMPLIED
>

<!ELEMENT SERVICE EMPTY>
<!ATTLIST SERVICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    PREPAIDMONTHS CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    SERVICETYPE CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    VALID CDATA #IMPLIED
>

<!ELEMENT SETTINGST EMPTY>
<!ATTLIST SETTINGST
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
>

<!ELEMENT SUPPLIER EMPTY>
<!ATTLIST SUPPLIER
    CERTIFIED CDATA #IMPLIED
    OVERALRATING CDATA #IMPLIED
    ID CDATA #REQUIRED
>

<!ELEMENT SUPPLIERBLACKLIST EMPTY>
<!ATTLIST SUPPLIERBLACKLIST
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CLIENT_ID CDATA #IMPLIED
>

<!ELEMENT SUPPLIERBLACKLIST_SUPPLIER EMPTY>
<!ATTLIST SUPPLIERBLACKLIST_SUPPLIER
    SUPPLIERBLACKLIST_ID CDATA #REQUIRED
    SUPPLIERS_ID CDATA #REQUIRED
>

<!ELEMENT SUPPLIER_AUD EMPTY>
<!ATTLIST SUPPLIER_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    CERTIFIED CDATA #IMPLIED
    OVERALRATING CDATA #IMPLIED
>

<!ELEMENT SUPPLIER_CATEGORY EMPTY>
<!ATTLIST SUPPLIER_CATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CATEGORY_ID CDATA #IMPLIED
    SUPPLIER_ID CDATA #IMPLIED
>

<!ELEMENT SUPPLIER_LOCALITY EMPTY>
<!ATTLIST SUPPLIER_LOCALITY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    LOCALITY_ID CDATA #IMPLIED
    SUPPLIER_ID CDATA #IMPLIED
>

<!ELEMENT TEMPLATE EMPTY>
<!ATTLIST TEMPLATE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    PREFILLEDINPUTS CDATA #IMPLIED
>

<!ELEMENT USERCONTACT EMPTY>
<!ATTLIST USERCONTACT
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CONTACTSTATUS CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    DISPLAYNAME CDATA #IMPLIED
    JOBTITLE CDATA #IMPLIED
    NOTE CDATA #IMPLIED
    REPRESENTS_ID CDATA #IMPLIED
    SAVEDBY_ID CDATA #IMPLIED
>

<!ELEMENT USERMESSAGE EMPTY>
<!ATTLIST USERMESSAGE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ISREAD CDATA #IMPLIED
    MESSAGECONTEXT CDATA #IMPLIED
    ROLETYPE CDATA #IMPLIED
    STARRED CDATA #IMPLIED
    MESSAGE_ID CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT USERSERVICE EMPTY>
<!ATTLIST USERSERVICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    SERVICE_ID CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT USERSERVICE_AUD EMPTY>
<!ATTLIST USERSERVICE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT USERT EMPTY>
<!ATTLIST USERT
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    EMAIL CDATA #REQUIRED
    PASSWORD CDATA #REQUIRED
    ACTIVATIONEMAIL_ID CDATA #IMPLIED
    SETTINGS_ID CDATA #REQUIRED
>

<!ELEMENT USERT_ACCESSROLE EMPTY>
<!ATTLIST USERT_ACCESSROLE
    USERT_ID CDATA #REQUIRED
    ACCESSROLES_ID CDATA #REQUIRED
>

<!ELEMENT USERT_AUD EMPTY>
<!ATTLIST USERT_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    PASSWORD CDATA #IMPLIED
>

=== RokLenarcic/poptavka/integration-test-base/src/main/resources/com/eprovement/poptavka/domain/user/ExternalUsersDataSet.xml
<!DOCTYPE dataset SYSTEM "../../../../../test.dtd">

<dataset>

    <SETTINGST ID="2" />
    <SETTINGST ID="9" />
    <SETTINGST ID="10" />

    <!-- Encrypted password corresponds to the "ahoj2" -->
    <USERT ID="111111112" EMAIL="velislav@email.com" PASSWORD="2ScrHmE5/qPHYSsYljrBNsMndlJLrvD5mWX+UkfTw2/GnAZsK77M6Cv9j9+WKNxB"
           SETTINGS_ID="2" ENABLED="1" VERIFICATION="VERIFIED" />
    <BUSINESSUSERDATA ID="111111112" COMPANYNAME="My Second Company" PERSONFIRSTNAME="Velislav" PERSONLASTNAME="Kroko"
                      CURRENTCREDITS="30" ENABLED="1"/>
    <BUSINESSUSER  ID="111111112" BUSINESSUSERDATA_ID="111111112"/>
    <BUSINESSUSERROLE ID="111111121" BUSINESSUSER_ID="111111112" ENABLED="1"/>
    <CLIENT ID="111111121" />


    <!-- external user that has pending notification (older than 30 days) -->
    <USERT ID="111111119" EMAIL="imported4@email.com" PASSWORD="ktWVVhGwWiMsAVgfbIZmX96r5WXBwIzMcGzwUBVAXcFvtiJutGRbKOk58TfQ4Wr2"
           SETTINGS_ID="9" ENABLED="1" VERIFICATION="UNVERIFIED" />
    <USERT_ACCESSROLE USERT_ID="111111119" ACCESSROLES_ID="2" />
    <BUSINESSUSERDATA ID="111111119" COMPANYNAME="My Fourth Company" PERSONFIRSTNAME="Imported" PERSONLASTNAME="User2"
                      TAXID="123" IDENTIFICATIONNUMBER="456" CURRENTCREDITS="30" ENABLED="1" />
    <!--origin with id = 1 is an external - see RegistersDataSet.xml -->
    <BUSINESSUSER  ID="111111119" BUSINESSUSERDATA_ID="111111119" ORIGIN_ID="1" />
    <ADDRESS ID="10"  CITY_ID="211" STREET="Test street 10" ZIPCODE="60200" />
    <BUSINESSUSER_ADDRESS BUSINESSUSER_ID="111111119" ADDRESSES_ID="10" />
    <USERNOTIFICATION ID="111111119" SENT="2014-02-01 13:33:33" NOTIFICATION_ID="13" USER_ID="111111119" ENABLED="1"/>
    <!-- User in role client-->
    <BUSINESSUSERROLE ID="111111991" BUSINESSUSER_ID="111111119" ENABLED="1"/>
    <!-- User in role supplier-->
    <BUSINESSUSERROLE ID="111111992" BUSINESSUSER_ID="111111119" ENABLED="1"/>
    <CLIENT ID="111111991" />
    <SUPPLIER ID="111111992" />


    <!-- external user that has pending notification (older than 30 days) -->
    <USERT ID="111111199" EMAIL="imported9@email.com" PASSWORD="ktWVVhGwWiMsAVgfbIZmX96r5WXBwIzMcGzwUBVAXcFvtiJutGRbKOk58TfQ4Wr2"
           SETTINGS_ID="10" ENABLED="1" VERIFICATION="UNVERIFIED" />
    <USERT_ACCESSROLE USERT_ID="111111199" ACCESSROLES_ID="2" />
    <BUSINESSUSERDATA ID="111111199" COMPANYNAME="My Ninth Company" PERSONFIRSTNAME="Imported" PERSONLASTNAME="User99"
                      TAXID="12399" IDENTIFICATIONNUMBER="45699" CURRENTCREDITS="30" ENABLED="1" />
    <!--origin with id = 1 is an external - see RegistersDataSet.xml -->
    <BUSINESSUSER  ID="111111199" BUSINESSUSERDATA_ID="111111199" ORIGIN_ID="1" />
    <ADDRESS ID="11"  CITY_ID="211" STREET="Test street 11" ZIPCODE="60200" />
    <BUSINESSUSER_ADDRESS BUSINESSUSER_ID="111111199" ADDRESSES_ID="11" />
    <USERNOTIFICATION ID="111111199" SENT="2014-02-01 13:33:33" NOTIFICATION_ID="14" USER_ID="111111199" ENABLED="1"/>
    <!-- User in role client-->
    <BUSINESSUSERROLE ID="111111993" BUSINESSUSER_ID="111111199" ENABLED="1"/>
    <!-- User in role supplier-->
    <BUSINESSUSERROLE ID="111111994" BUSINESSUSER_ID="111111199" ENABLED="1"/>
    <CLIENT ID="111111993" />
    <SUPPLIER ID="111111994" />

    <!-- Potential Demand that matches external suppliers above -->
    <DEMAND ID="99" TYPE_ID="2" TITLE="Demand 99" DESCRIPTION="99: demand description for offered testing." PRICE="10000"
            STATUS="ACTIVE" CLIENT_ID="111111121" CREATEDDATE="2010-10-01 13:33:34"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2019-12-01 13:33:33" />
    <DEMANDTYPE ID="2" CODE="attractive" />
    <DEMAND_LOCALITY ID="99" DEMAND_ID="99" LOCALITY_ID="2" />  <!-- "locality2"-->
    <DEMAND_CATEGORY ID="99" DEMAND_ID="99" CATEGORY_ID="1132" /> <!-- "Category 1132" -->
    <MESSAGE ID="999"
             CREATED="2011-05-11"
             BODY="test for external supplier."
             PARENT_ID="[NULL]"
             SENDER_ID="111111112"
             FIRSTBORN_ID="[NULL]"
             THREADROOT_ID="999"
             SUBJECT="demand for externl supplier"
             DEMAND_ID="99" />
    <SUPPLIER_LOCALITY ID="990" SUPPLIER_ID="111111992" LOCALITY_ID="2" />
    <SUPPLIER_CATEGORY ID="990" SUPPLIER_ID="111111992" CATEGORY_ID="1132" />
    <SUPPLIER_LOCALITY ID="991" SUPPLIER_ID="111111994" LOCALITY_ID="2" />
    <SUPPLIER_CATEGORY ID="991" SUPPLIER_ID="111111994" CATEGORY_ID="1132" />

</dataset>

=== RokLenarcic/poptavka/poptavka-core/src/test/resources/cz/poptavka/sample/domain/message/MessageDataSet.xml
<!DOCTYPE dataset SYSTEM "../../../../test.dtd">
        <!-- This data set uses objects defined in UserDataSet.xml -->
<dataset>

    <!-- Thread root -->
    <MESSAGE ID="1"
             CREATED="2011-05-11"
             BODY="Ahoj, teta, dnes mam vela prace, budem spat u kamaratky.\nZajtra sa zastavim pre tu slivovicu."
             PARENT_ID="[NULL]"
             SENDER_ID="111111112"
             FIRSTBORN_ID="3"
             SUBJECT="Dnes nepridem - zajtra" />

    <!-- Reply to the original (thread root) message -->
    <MESSAGE ID="3" BODY="Ahoj, Kamilko, slivovička je pripravená. Dávaj si na seba pozor. "
             CREATED="2011-05-11"
             PARENT_ID="1"
             SUBJECT="Re: Dnes nepridem - zajtra "
             SENDER_ID="111111111"
             FIRSTBORN_ID="2"
             THREADROOT_ID="1" />

    <!-- Reply to the reply of original (thread root) message -->
    <MESSAGE ID="2"
             CREATED="2011-05-12"
             BODY="Ahoj, teta, viem, ze som vcera pisal, ze dnes pridem, ale opat nemozem - snad zajtra :). "
             SUBJECT="Re: Re: Dnes nepridem - zajtra "
             PARENT_ID="3"
             SENDER_ID="111111112"
             NEXTSIBLING_ID="4"
             THREADROOT_ID="1" />

    <!-- Second Reply to the reply to the original (thread root) message -->
    <MESSAGE ID="4"
             CREATED="2011-05-12"
             SUBJECT="Re: Re: Dnes nepridem - zajtra - ZMENA!"
             BODY="Ahoj, teta, opat zmena - predsa len dojdem dnes pre tu slivovicu!"
             PARENT_ID="3"
             SENDER_ID="111111112"
             THREADROOT_ID="1" />

    <MESSAGEUSERROLE ID="1" MESSAGE_ID="1" USER_ID="111111112" TYPE="SENDER"/>
    <MESSAGEUSERROLE ID="2" MESSAGE_ID="1" USER_ID="111111111" TYPE="TO"/>
    <MESSAGEUSERROLE ID="3" MESSAGE_ID="2" USER_ID="111111112" TYPE="SENDER"/>
    <MESSAGEUSERROLE ID="4" MESSAGE_ID="2" USER_ID="111111111" TYPE="TO"/>
    <MESSAGEUSERROLE ID="5" MESSAGE_ID="3" USER_ID="111111111" TYPE="SENDER"/>
    <MESSAGEUSERROLE ID="6" MESSAGE_ID="3" USER_ID="111111112" TYPE="TO"/>
    <MESSAGEUSERROLE ID="7" MESSAGE_ID="4" USER_ID="111111112" TYPE="SENDER"/>
    <MESSAGEUSERROLE ID="8" MESSAGE_ID="4" USER_ID="111111111" TYPE="TO"/>


    !-- Completely different Thread root -->
    <MESSAGE ID="5"
             BODY="Ahoj, ahoj, ahoj, dnes, kupit, slivowitz."
             PARENT_ID="[NULL]"
             SUBJECT="Spam - ahoj, ahoj" />

</dataset>
