=== RokLenarcic/poptavka/integration-test-base/src/main/resources/test.dtd
<!ELEMENT dataset (
    ACCESSROLE*,
    ACCESS_ROLE_PERMISSION*,
    ACTION*,
    ACTIVATIONEMAIL*,
    ADDRESS*,
    ADVICE*,
    BASICAUDITINFO*,
    BUSINESSUSER*,
    BUSINESSUSERDATA*,
    BUSINESSUSERDATA_AUD*,
    BUSINESSUSERROLE*,
    BUSINESSUSERROLE_AUD*,
    BUSINESSUSER_ADDRESS*,
    BUSINESSUSER_AUD*,
    BUSINESSUSER_INVOICE*,
    CATEGORY*,
    CLIENT*,
    CLIENT_AUD*,
    DEMAND*,
    DEMANDTYPE*,
    DEMANDTYPE_AUD*,
    DEMAND_AUD*,
    DEMAND_CATEGORY*,
    DEMAND_EXCLUDED_SUPPLIER*,
    DEMAND_EXCLUDED_SUPPLIER_AUD*,
    DEMAND_LOCALITY*,
    EXTERNALCATEGORY*,
    EXTERNALSOURCE*,
    EXTERNAL_CATEGORY_TO_CATEGORY*,
    INVOICE*,
    INVOICE_USERSERVICE*,
    LOCALITY*,
    MESSAGE*,
    MESSAGEUSERROLE*,
    NOTIFICATION*,
    NOTIFICATIONITEM*,
    OFFER*,
    OFFERSTATE*,
    ORIGIN*,
    OURPAYMENTDETAILS*,
    OURPAYMENTDETAILS_AUD*,
    PARTNER*,
    PARTNER_AUD*,
    PAYMENTMETHOD*,
    PERMISSION*,
    PREFERENCE*,
    PREFERENCE_AUD*,
    PROBLEM*,
    PROBLEM_AUD*,
    RATING*,
    REGIONABBREVIATION*,
    REVINFO*,
    SERVICE*,
    SETTINGST*,
    SUPPLIER*,
    SUPPLIERBLACKLIST*,
    SUPPLIERBLACKLIST_SUPPLIER*,
    SUPPLIER_AUD*,
    SUPPLIER_CATEGORY*,
    SUPPLIER_LOCALITY*,
    TEMPLATE*,
    USERCONTACT*,
    USERMESSAGE*,
    USERSERVICE*,
    USERSERVICE_AUD*,
    USERT*,
    USERT_ACCESSROLE*,
    USERT_AUD*)>

<!ELEMENT ACCESSROLE EMPTY>
<!ATTLIST ACCESSROLE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT ACCESS_ROLE_PERMISSION EMPTY>
<!ATTLIST ACCESS_ROLE_PERMISSION
    ACCESSROLE_ID CDATA #REQUIRED
    PERMISSIONS_ID CDATA #REQUIRED
>

<!ELEMENT ACTION EMPTY>
<!ATTLIST ACTION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT ACTIVATIONEMAIL EMPTY>
<!ATTLIST ACTIVATIONEMAIL
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ACTIVATIONCODE CDATA #IMPLIED
    VALIDTO CDATA #IMPLIED
>

<!ELEMENT ADDRESS EMPTY>
<!ATTLIST ADDRESS
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ADDRESSTYPE CDATA #IMPLIED
    FLATNUM CDATA #IMPLIED
    HOUSENUM CDATA #IMPLIED
    STREET CDATA #REQUIRED
    ZIPCODE CDATA #IMPLIED
    CITY_ID CDATA #REQUIRED
>

<!ELEMENT ADVICE EMPTY>
<!ATTLIST ADVICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    BOUNTY CDATA #IMPLIED
    PAYMENTDATE CDATA #IMPLIED
    RECOGNIZED CDATA #IMPLIED
    REMITTERACCOUNT CDATA #IMPLIED
    REMITTERNAME CDATA #IMPLIED
    REMITTERSURNAME CDATA #IMPLIED
    VARIABLESYMBOL CDATA #IMPLIED
    INVOICE_ID CDATA #IMPLIED
>

<!ELEMENT BASICAUDITINFO EMPTY>
<!ATTLIST BASICAUDITINFO
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    INSERTTIME CDATA #IMPLIED
    MODIFICATIONTIME CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    USERIDCREATED CDATA #IMPLIED
    USERIDMODIFIED CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSER EMPTY>
<!ATTLIST BUSINESSUSER
    BUSINESSTYPE CDATA #IMPLIED
    ID CDATA #REQUIRED
    BUSINESSUSERDATA_ID CDATA #REQUIRED
    ORIGIN_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERDATA EMPTY>
<!ATTLIST BUSINESSUSERDATA
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    COMPANYNAME CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PERSONFIRSTNAME CDATA #REQUIRED
    PERSONLASTNAME CDATA #REQUIRED
    PHONE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    WEBSITE CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERDATA_AUD EMPTY>
<!ATTLIST BUSINESSUSERDATA_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    COMPANYNAME CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PERSONFIRSTNAME CDATA #IMPLIED
    PERSONLASTNAME CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    WEBSITE CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERROLE EMPTY>
<!ATTLIST BUSINESSUSERROLE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    VERIFICATION CDATA #IMPLIED
    BUSINESSUSER_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSERROLE_AUD EMPTY>
<!ATTLIST BUSINESSUSERROLE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    VERIFICATION CDATA #IMPLIED
    BUSINESSUSER_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSER_ADDRESS EMPTY>
<!ATTLIST BUSINESSUSER_ADDRESS
    BUSINESSUSER_ID CDATA #REQUIRED
    ADDRESSES_ID CDATA #REQUIRED
>

<!ELEMENT BUSINESSUSER_AUD EMPTY>
<!ATTLIST BUSINESSUSER_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    BUSINESSTYPE CDATA #IMPLIED
    BUSINESSUSERDATA_ID CDATA #IMPLIED
>

<!ELEMENT BUSINESSUSER_INVOICE EMPTY>
<!ATTLIST BUSINESSUSER_INVOICE
    BUSINESSUSER_ID CDATA #REQUIRED
    INVOICES_ID CDATA #REQUIRED
>

<!ELEMENT CATEGORY EMPTY>
<!ATTLIST CATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    LEFTBOUND CDATA #IMPLIED
    LEVEL CDATA #REQUIRED
    RIGHTBOUND CDATA #IMPLIED
    TREEID CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
    PARENT_ID CDATA #IMPLIED
    TEMPLATE_ID CDATA #IMPLIED
>

<!ELEMENT CLIENT EMPTY>
<!ATTLIST CLIENT
    OVERALRATING CDATA #IMPLIED
    ID CDATA #REQUIRED
>

<!ELEMENT CLIENT_AUD EMPTY>
<!ATTLIST CLIENT_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    OVERALRATING CDATA #IMPLIED
>

<!ELEMENT DEMAND EMPTY>
<!ATTLIST DEMAND
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ATTACHMENTPATH CDATA #IMPLIED
    CREATEDDATE CDATA #IMPLIED
    DESCRIPTION CDATA #REQUIRED
    ENDDATE CDATA #IMPLIED
    MAXSUPPLIERS CDATA #IMPLIED
    MINRATING CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    STATUS CDATA #REQUIRED
    TITLE CDATA #REQUIRED
    VALIDTO CDATA #IMPLIED
    CLIENT_ID CDATA #IMPLIED
    ORIGIN_ID CDATA #IMPLIED
    RATING_ID CDATA #IMPLIED
    TYPE_ID CDATA #REQUIRED
>

<!ELEMENT DEMANDTYPE EMPTY>
<!ATTLIST DEMANDTYPE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT DEMANDTYPE_AUD EMPTY>
<!ATTLIST DEMANDTYPE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT DEMAND_AUD EMPTY>
<!ATTLIST DEMAND_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    ATTACHMENTPATH CDATA #IMPLIED
    CREATEDDATE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    ENDDATE CDATA #IMPLIED
    MAXSUPPLIERS CDATA #IMPLIED
    MINRATING CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    VALIDTO CDATA #IMPLIED
    CLIENT_ID CDATA #IMPLIED
    TYPE_ID CDATA #IMPLIED
>

<!ELEMENT DEMAND_CATEGORY EMPTY>
<!ATTLIST DEMAND_CATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CATEGORY_ID CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
>

<!ELEMENT DEMAND_EXCLUDED_SUPPLIER EMPTY>
<!ATTLIST DEMAND_EXCLUDED_SUPPLIER
    DEMAND_ID CDATA #REQUIRED
    SUPPLIER_ID CDATA #REQUIRED
>

<!ELEMENT DEMAND_EXCLUDED_SUPPLIER_AUD EMPTY>
<!ATTLIST DEMAND_EXCLUDED_SUPPLIER_AUD
    REV CDATA #REQUIRED
    DEMAND_ID CDATA #REQUIRED
    SUPPLIER_ID CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
>

<!ELEMENT DEMAND_LOCALITY EMPTY>
<!ATTLIST DEMAND_LOCALITY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
    LOCALITY_ID CDATA #IMPLIED
>

<!ELEMENT EXTERNALCATEGORY EMPTY>
<!ATTLIST EXTERNALCATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    EXTERNALID CDATA #REQUIRED
    EXTERNALSOURCE_ID CDATA #IMPLIED
>

<!ELEMENT EXTERNALSOURCE EMPTY>
<!ATTLIST EXTERNALSOURCE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    URL CDATA #IMPLIED
>

<!ELEMENT EXTERNAL_CATEGORY_TO_CATEGORY EMPTY>
<!ATTLIST EXTERNAL_CATEGORY_TO_CATEGORY
    EXTERNAL_CATEGORY_ID CDATA #REQUIRED
    CATEGORY_ID CDATA #REQUIRED
>

<!ELEMENT INVOICE EMPTY>
<!ATTLIST INVOICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BANKACCOUNTNUMBER CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    CONSTSYMBOL CDATA #IMPLIED
    DUEDATE CDATA #IMPLIED
    INVOICENUMBER CDATA #IMPLIED
    ISSUEDATE CDATA #IMPLIED
    SHIPMENTDATE CDATA #IMPLIED
    TAXBASIS CDATA #IMPLIED
    TOTALPRICE CDATA #IMPLIED
    VARIABLESYMBOL CDATA #IMPLIED
    VAT CDATA #IMPLIED
    VATRATE CDATA #REQUIRED
    PAYMENTMETHOD_ID CDATA #IMPLIED
>

<!ELEMENT INVOICE_USERSERVICE EMPTY>
<!ATTLIST INVOICE_USERSERVICE
    INVOICE_ID CDATA #REQUIRED
    USERSERVICES_ID CDATA #REQUIRED
>

<!ELEMENT LOCALITY EMPTY>
<!ATTLIST LOCALITY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    LEFTBOUND CDATA #IMPLIED
    LEVEL CDATA #REQUIRED
    RIGHTBOUND CDATA #IMPLIED
    TREEID CDATA #IMPLIED
    NAME CDATA #IMPLIED
    TYPE CDATA #IMPLIED
    PARENT_ID CDATA #IMPLIED
>

<!ELEMENT MESSAGE EMPTY>
<!ATTLIST MESSAGE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BODY CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    LASTMODIFIED CDATA #IMPLIED
    MESSAGESTATE CDATA #IMPLIED
    SENT CDATA #IMPLIED
    SUBJECT CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
    FIRSTBORN_ID CDATA #IMPLIED
    NEXTSIBLING_ID CDATA #IMPLIED
    OFFER_ID CDATA #IMPLIED
    PARENT_ID CDATA #IMPLIED
    PROBLEM_ID CDATA #IMPLIED
    SENDER_ID CDATA #IMPLIED
    THREADROOT_ID CDATA #IMPLIED
>

<!ELEMENT MESSAGEUSERROLE EMPTY>
<!ATTLIST MESSAGEUSERROLE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    MESSAGECONTEXT CDATA #IMPLIED
    TYPE CDATA #IMPLIED
    MESSAGE_ID CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT NOTIFICATION EMPTY>
<!ATTLIST NOTIFICATION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    MESSAGETEMPLATE CDATA #IMPLIED
    NAME CDATA #IMPLIED
    NOTIFICATIONTYPE CDATA #IMPLIED
>

<!ELEMENT NOTIFICATIONITEM EMPTY>
<!ATTLIST NOTIFICATIONITEM
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    PERIOD CDATA #IMPLIED
    NOTIFICATION_ID CDATA #IMPLIED
    SETTINGS_ID CDATA #IMPLIED
>

<!ELEMENT OFFER EMPTY>
<!ATTLIST OFFER
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    FINISHDATE CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    DEMAND_ID CDATA #IMPLIED
    STATE_ID CDATA #IMPLIED
    SUPPLIER_ID CDATA #IMPLIED
>

<!ELEMENT OFFERSTATE EMPTY>
<!ATTLIST OFFERSTATE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT ORIGIN EMPTY>
<!ATTLIST ORIGIN
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
    URL CDATA #IMPLIED
>

<!ELEMENT OURPAYMENTDETAILS EMPTY>
<!ATTLIST OURPAYMENTDETAILS
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    BANKACCOUNT CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    CITY CDATA #IMPLIED
    COUNTRYVAT CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    IBAN CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    STREET CDATA #IMPLIED
    SWIFTCODE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    ZIPCODE CDATA #IMPLIED
>

<!ELEMENT OURPAYMENTDETAILS_AUD EMPTY>
<!ATTLIST OURPAYMENTDETAILS_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    BANKACCOUNT CDATA #IMPLIED
    BANKCODE CDATA #IMPLIED
    CITY CDATA #IMPLIED
    COUNTRYVAT CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    IBAN CDATA #IMPLIED
    IDENTIFICATIONNUMBER CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    STREET CDATA #IMPLIED
    SWIFTCODE CDATA #IMPLIED
    TAXID CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    ZIPCODE CDATA #IMPLIED
>

<!ELEMENT PARTNER EMPTY>
<!ATTLIST PARTNER
    ID CDATA #REQUIRED
>

<!ELEMENT PARTNER_AUD EMPTY>
<!ATTLIST PARTNER_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
>

<!ELEMENT PAYMENTMETHOD EMPTY>
<!ATTLIST PAYMENTMETHOD
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT PERMISSION EMPTY>
<!ATTLIST PERMISSION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    NAME CDATA #IMPLIED
>

<!ELEMENT PREFERENCE EMPTY>
<!ATTLIST PREFERENCE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    PKEY CDATA #IMPLIED
    VALUE CDATA #IMPLIED
    SETTINGS_ID CDATA #IMPLIED
>

<!ELEMENT PREFERENCE_AUD EMPTY>
<!ATTLIST PREFERENCE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    PKEY CDATA #IMPLIED
    VALUE CDATA #IMPLIED
>

<!ELEMENT PROBLEM EMPTY>
<!ATTLIST PROBLEM
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    TEXT CDATA #IMPLIED
>

<!ELEMENT PROBLEM_AUD EMPTY>
<!ATTLIST PROBLEM_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    TEXT CDATA #IMPLIED
>

<!ELEMENT RATING EMPTY>
<!ATTLIST RATING
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CLIENTMESSAGE CDATA #IMPLIED
    CLIENTRATING CDATA #IMPLIED
    SUPPLIERMESSAGE CDATA #IMPLIED
    SUPPLIERRATING CDATA #IMPLIED
>

<!ELEMENT REGIONABBREVIATION EMPTY>
<!ATTLIST REGIONABBREVIATION
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ABBREVIATION CDATA #IMPLIED
    REGION_ID CDATA #IMPLIED
>

<!ELEMENT REVINFO EMPTY>
<!ATTLIST REVINFO
    REV CDATA #REQUIRED
    REVTSTMP CDATA #IMPLIED
>

<!ELEMENT SERVICE EMPTY>
<!ATTLIST SERVICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CODE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    PREPAIDMONTHS CDATA #IMPLIED
    PRICE CDATA #IMPLIED
    SERVICETYPE CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    VALID CDATA #IMPLIED
>

<!ELEMENT SETTINGST EMPTY>
<!ATTLIST SETTINGST
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
>

<!ELEMENT SUPPLIER EMPTY>
<!ATTLIST SUPPLIER
    CERTIFIED CDATA #IMPLIED
    OVERALRATING CDATA #IMPLIED
    ID CDATA #REQUIRED
>

<!ELEMENT SUPPLIERBLACKLIST EMPTY>
<!ATTLIST SUPPLIERBLACKLIST
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CLIENT_ID CDATA #IMPLIED
>

<!ELEMENT SUPPLIERBLACKLIST_SUPPLIER EMPTY>
<!ATTLIST SUPPLIERBLACKLIST_SUPPLIER
    SUPPLIERBLACKLIST_ID CDATA #REQUIRED
    SUPPLIERS_ID CDATA #REQUIRED
>

<!ELEMENT SUPPLIER_AUD EMPTY>
<!ATTLIST SUPPLIER_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    CERTIFIED CDATA #IMPLIED
    OVERALRATING CDATA #IMPLIED
>

<!ELEMENT SUPPLIER_CATEGORY EMPTY>
<!ATTLIST SUPPLIER_CATEGORY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CATEGORY_ID CDATA #IMPLIED
    SUPPLIER_ID CDATA #IMPLIED
>

<!ELEMENT SUPPLIER_LOCALITY EMPTY>
<!ATTLIST SUPPLIER_LOCALITY
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    LOCALITY_ID CDATA #IMPLIED
    SUPPLIER_ID CDATA #IMPLIED
>

<!ELEMENT TEMPLATE EMPTY>
<!ATTLIST TEMPLATE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    PREFILLEDINPUTS CDATA #IMPLIED
>

<!ELEMENT USERCONTACT EMPTY>
<!ATTLIST USERCONTACT
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    CONTACTSTATUS CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    DISPLAYNAME CDATA #IMPLIED
    JOBTITLE CDATA #IMPLIED
    NOTE CDATA #IMPLIED
    REPRESENTS_ID CDATA #IMPLIED
    SAVEDBY_ID CDATA #IMPLIED
>

<!ELEMENT USERMESSAGE EMPTY>
<!ATTLIST USERMESSAGE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    ISREAD CDATA #IMPLIED
    MESSAGECONTEXT CDATA #IMPLIED
    ROLETYPE CDATA #IMPLIED
    STARRED CDATA #IMPLIED
    MESSAGE_ID CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT USERSERVICE EMPTY>
<!ATTLIST USERSERVICE
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    SERVICE_ID CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT USERSERVICE_AUD EMPTY>
<!ATTLIST USERSERVICE_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    USER_ID CDATA #IMPLIED
>

<!ELEMENT USERT EMPTY>
<!ATTLIST USERT
    ID CDATA #REQUIRED
    ENABLED CDATA #IMPLIED
    EMAIL CDATA #REQUIRED
    PASSWORD CDATA #REQUIRED
    ACTIVATIONEMAIL_ID CDATA #IMPLIED
    SETTINGS_ID CDATA #REQUIRED
>

<!ELEMENT USERT_ACCESSROLE EMPTY>
<!ATTLIST USERT_ACCESSROLE
    USERT_ID CDATA #REQUIRED
    ACCESSROLES_ID CDATA #REQUIRED
>

<!ELEMENT USERT_AUD EMPTY>
<!ATTLIST USERT_AUD
    ID CDATA #REQUIRED
    REV CDATA #REQUIRED
    REVTYPE CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    PASSWORD CDATA #IMPLIED
>

=== RokLenarcic/poptavka/integration-test-base/src/main/resources/com/eprovement/poptavka/domain/user/SupplierDataSet.xml
<!DOCTYPE dataset SYSTEM "../../../../../test.dtd">
<dataset>

    <SETTINGST ID="11" />
    <SETTINGST ID="12" />
    <SETTINGST ID="13" />
    <SETTINGST ID="14" />
    <SETTINGST ID="15" />

    <!--################################ Suppliers ##################################################################-->
    <USERT ID="11" EMAIL="elvira11@email.com" PASSWORD="ahoj" SETTINGS_ID="11" VERIFICATION="UNVERIFIED" />
    <BUSINESSUSERDATA ID="11" COMPANYNAME="My First Company" PERSONFIRSTNAME="Elvíra" PERSONLASTNAME="Vytretá"/>
    <BUSINESSUSER  ID="11" BUSINESSUSERDATA_ID="11"/>
    <BUSINESSUSERROLE ID="11" BUSINESSUSER_ID="11" />
    <CLIENT ID="11" />
    <SUPPLIER ID="11" />

    <USERT ID="12" EMAIL="velislav12@email.com" PASSWORD="ahoj" SETTINGS_ID="12" VERIFICATION="UNVERIFIED" />
    <BUSINESSUSERDATA ID="12" COMPANYNAME="My Second Company" PERSONFIRSTNAME="Velislav" PERSONLASTNAME="Kroko" />
    <BUSINESSUSER  ID="12" BUSINESSUSERDATA_ID="12"/>
    <BUSINESSUSERROLE ID="12" BUSINESSUSER_ID="12" />
    <CLIENT ID="12" />
    <SUPPLIER ID="12" />

    <USERT ID="13" EMAIL="lisohlavka12@email.com" PASSWORD="ahoj" SETTINGS_ID="13" VERIFICATION="UNVERIFIED" />
    <BUSINESSUSERDATA ID="13" COMPANYNAME="My Third Company" PERSONFIRSTNAME="Lisohlávka" PERSONLASTNAME="Čínska"/>
    <BUSINESSUSER ID="13" BUSINESSUSERDATA_ID="13"/>
    <BUSINESSUSERROLE ID="13" BUSINESSUSER_ID="13" />
    <CLIENT ID="13" />
    <SUPPLIER ID="13" />

    <USERT ID="14" EMAIL="elvira14@email.com" PASSWORD="ahoj" SETTINGS_ID="14" VERIFICATION="UNVERIFIED" />
    <BUSINESSUSERDATA ID="14" COMPANYNAME="My Fourth Company" TAXID="hovna" IDENTIFICATIONNUMBER="sracky" PERSONFIRSTNAME="Elvíra" PERSONLASTNAME="Maslová"/>
    <BUSINESSUSER  ID="14"  BUSINESSUSERDATA_ID="14" />
    <BUSINESSUSERROLE ID="14" BUSINESSUSER_ID="14" />
    <CLIENT ID="14" />
    <SUPPLIER ID="14" />

    <!-- User/BusinessUserRole-s with id=15 are disabled and shouldn't be involved in supplier related queries-->
    <USERT ID="15" EMAIL="importedSupplier15@email.com" PASSWORD="imported" SETTINGS_ID="15" VERIFICATION="UNVERIFIED" ENABLED="0" />
    <BUSINESSUSERDATA ID="15" COMPANYNAME="My Fifthe Company imported to WS" TAXID="123" IDENTIFICATIONNUMBER="12309892" PERSONFIRSTNAME="Ivan" PERSONLASTNAME="Importovany" ENABLED="0" />
    <BUSINESSUSER  ID="15"  BUSINESSUSERDATA_ID="15" />
    <BUSINESSUSERROLE ID="15" BUSINESSUSER_ID="15" ENABLED="0" />
    <CLIENT ID="15" ENABLED="0" />
    <SUPPLIER ID="15" ENABLED="0" />


    <!--################################ Suppliers to Localities#####################################################-->
    <!-- loc1 && loc213 -->
    <SUPPLIER_LOCALITY ID="1" SUPPLIER_ID="11" LOCALITY_ID="1" />
    <SUPPLIER_LOCALITY ID="2" SUPPLIER_ID="11" LOCALITY_ID="213" />

    <SUPPLIER_LOCALITY ID="3" SUPPLIER_ID="12" LOCALITY_ID="2" />
    <SUPPLIER_LOCALITY ID="4" SUPPLIER_ID="13" LOCALITY_ID="11" />
    <SUPPLIER_LOCALITY ID="5" SUPPLIER_ID="14" LOCALITY_ID="21" />
    <!-- supplier_locality id=10 is disabled and it shouldn't be involved in supplier related queries-->
    <SUPPLIER_LOCALITY ID="10" SUPPLIER_ID="15" LOCALITY_ID="21" ENABLED="0" />


    <!--################################ Suppliers to Categories#####################################################-->
    <SUPPLIER_CATEGORY ID="6" SUPPLIER_ID="11" CATEGORY_ID="3" />
    <SUPPLIER_CATEGORY ID="7" SUPPLIER_ID="12" CATEGORY_ID="11" />
    <SUPPLIER_CATEGORY ID="8" SUPPLIER_ID="13" CATEGORY_ID="113" />
    <SUPPLIER_CATEGORY ID="9" SUPPLIER_ID="14" CATEGORY_ID="312" />
    <!-- supplier_category id=11 is disabled and it shouldn't be involved in supplier related queries-->
    <SUPPLIER_CATEGORY ID="11" SUPPLIER_ID="15" CATEGORY_ID="312" ENABLED="0" />

</dataset>

=== RokLenarcic/poptavka/integration-test-base/src/main/resources/com/eprovement/poptavka/domain/demand/DemandDataSet.xml
<!DOCTYPE dataset SYSTEM "../../../../../test.dtd">

<dataset>
    <!--############################################ demands ########################################################-->

    <DEMANDTYPE ID="1" CODE="normal" />
    <DEMANDTYPE ID="2" CODE="attractive" />
    <DEMANDTYPE ID="3" CODE="all" />

    <DEMAND ID="1" TYPE_ID="1" TITLE="Demand 1" DESCRIPTION="1: Normal request for java application."        PRICE="10000"
            STATUS="NEW" RATING_ID="1" CLIENT_ID="111111121" CREATEDDATE="2011-11-01 13:33:33"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="2" TYPE_ID="2" TITLE="Demand 2" DESCRIPTION="2: Attractive request for java application."    PRICE="10000"
            STATUS="ACTIVE" RATING_ID="2" CLIENT_ID="111111121" CREATEDDATE="2011-11-02 00:00:01"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="3" TYPE_ID="1" TITLE="Demand 3" DESCRIPTION="3: All request for java application."           PRICE="1200"
            STATUS="INVALID" RATING_ID="3" CLIENT_ID="111111131" CREATEDDATE="2001-01-01 00:00:01"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="4" TYPE_ID="1" TITLE="Demand 4" DESCRIPTION="4: Normal request for java application."
            STATUS="INVALID" RATING_ID="4" CLIENT_ID="111111141" CREATEDDATE="2001-01-01 00:00:01"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="5" TYPE_ID="2" TITLE="Demand 5" DESCRIPTION="5: Attractive request for java application."
            STATUS="INVALID"                                                  CREATEDDATE="2010-10-01 13:33:33"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="6" TYPE_ID="1" TITLE="Demand 6" DESCRIPTION="6: All request for java application."           PRICE="444"
            STATUS="INVALID" CREATEDDATE="2001-01-01 00:00:01"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="7" TYPE_ID="1" TITLE="Demand 7" DESCRIPTION="7: Normal request for java application."        PRICE="1110"
            STATUS="NEW" CREATEDDATE="2001-01-01 00:00:01"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="8" TYPE_ID="1" TITLE="Demand 8" DESCRIPTION="8: Normal request for java application."        PRICE="9000000"
            STATUS="ACTIVE" CREATEDDATE="2001-01-01 00:00:01" CLIENT_ID="111111141"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <!--demand with id 18 is the same as with id 8 bus has status NEW -->
    <DEMAND ID="18" TYPE_ID="1" TITLE="Demand 8" DESCRIPTION="8: Normal request for java application."        PRICE="9000000"
            STATUS="NEW" CREATEDDATE="2001-01-01 00:00:01"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="9" TYPE_ID="1" TITLE="Demand 9" DESCRIPTION="9: Normal request for java application." PRICE="10000"
            STATUS="ACTIVE" CREATEDDATE="2001-01-01 00:00:01" CLIENT_ID="111111121"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="10" TYPE_ID="2" TITLE="Demand 10" DESCRIPTION="10: Attractive request for java application." PRICE="10000"
            STATUS="ACTIVE" CREATEDDATE="2010-10-01 13:33:34" CLIENT_ID="111111121"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="11" TYPE_ID="2" TITLE="Demand 11" DESCRIPTION="11: want something from want-something.com." PRICE="10000"
            STATUS="CLOSED" CLIENT_ID="111111151" CREATEDDATE="2010-10-01 13:33:34"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />

    <DEMAND ID="21" TYPE_ID="1" TITLE="Demand 9" DESCRIPTION="21: Normal request for java application."
            STATUS="ACTIVE" CREATEDDATE="2001-01-01 00:00:01" CLIENT_ID="111111121"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="22" TYPE_ID="2" TITLE="Demand 10" DESCRIPTION="22: Attractive request for java application." PRICE="10000"
            STATUS="OFFERED" CREATEDDATE="2010-10-01 13:33:34" CLIENT_ID="111111121"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="23" TYPE_ID="2" TITLE="Demand 11" DESCRIPTION="23: want something from want-something.com." PRICE="10000"
            STATUS="CLOSED" CLIENT_ID="111111121" CREATEDDATE="2010-10-01 13:33:34"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />
    <DEMAND ID="70" TYPE_ID="2" TITLE="Demand 70" DESCRIPTION="70: demand description for offered testing." PRICE="10000"
            STATUS="OFFERED" CLIENT_ID="111111121" CREATEDDATE="2010-10-01 13:33:34"
            ENDDATE="2011-12-01 13:33:33" VALIDTO="2011-12-01 13:33:33" />



    <!--########################################## demands for localities ###########################################-->
    <DEMAND_LOCALITY ID="1" DEMAND_ID="1" LOCALITY_ID="1" />   <!-- "locality1"-->
    <DEMAND_LOCALITY ID="2" DEMAND_ID="2" LOCALITY_ID="2" />   <!-- "locality2"-->
    <DEMAND_LOCALITY ID="3" DEMAND_ID="3" LOCALITY_ID="2" />   <!-- "locality2"-->
    <DEMAND_LOCALITY ID="4" DEMAND_ID="4" LOCALITY_ID="11" />   <!-- "locality11"-->
    <DEMAND_LOCALITY ID="5" DEMAND_ID="5" LOCALITY_ID="11" />   <!-- "locality11"-->
    <DEMAND_LOCALITY ID="6" DEMAND_ID="6" LOCALITY_ID="11" />   <!-- "locality11"-->
    <DEMAND_LOCALITY ID="7" DEMAND_ID="7" LOCALITY_ID="11" />   <!-- "locality11"-->
    <DEMAND_LOCALITY ID="8" DEMAND_ID="8" LOCALITY_ID="121" />   <!-- "locality121"-->
    <DEMAND_LOCALITY ID="18" DEMAND_ID="18" LOCALITY_ID="121" />   <!-- "locality121"-->
    <DEMAND_LOCALITY ID="9" DEMAND_ID="9" LOCALITY_ID="21" />   <!-- "locality21"-->
    <DEMAND_LOCALITY ID="10" DEMAND_ID="10" LOCALITY_ID="2" />  <!-- "locality2"-->
    <DEMAND_LOCALITY ID="11" DEMAND_ID="11" LOCALITY_ID="2" />  <!-- "locality2"-->

    <!--########################################## demands for categories ###########################################-->
    <DEMAND_CATEGORY ID="1" DEMAND_ID="1" CATEGORY_ID="0" /> <!-- "Root category" -->
    <DEMAND_CATEGORY ID="2" DEMAND_ID="2" CATEGORY_ID="1" /> <!-- "Category 1" -->
    <DEMAND_CATEGORY ID="3" DEMAND_ID="3" CATEGORY_ID="2" /> <!-- "Category 2" -->
    <DEMAND_CATEGORY ID="4" DEMAND_ID="4" CATEGORY_ID="3" /> <!-- "Category 3" -->
    <DEMAND_CATEGORY ID="5" DEMAND_ID="5" CATEGORY_ID="11" /> <!-- "Category 11" -->
    <DEMAND_CATEGORY ID="6" DEMAND_ID="6" CATEGORY_ID="11" /> <!-- "Category 11" -->
    <DEMAND_CATEGORY ID="7" DEMAND_ID="7" CATEGORY_ID="31" /> <!-- "Category 31" -->
    <DEMAND_CATEGORY ID="8" DEMAND_ID="8" CATEGORY_ID="112" /> <!-- "Category 112" -->
    <DEMAND_CATEGORY ID="18" DEMAND_ID="18" CATEGORY_ID="112" /> <!-- "Category 112" -->
    <DEMAND_CATEGORY ID="9" DEMAND_ID="9" CATEGORY_ID="312" /> <!-- "Category 312" -->
    <DEMAND_CATEGORY ID="10" DEMAND_ID="10" CATEGORY_ID="1132" /> <!-- "Category 1132" -->
    <DEMAND_CATEGORY ID="11" DEMAND_ID="11" CATEGORY_ID="1132" /> <!-- "Category 1132" -->

</dataset>
